baseURL = 'https://mattmc3.github.io/'
languageCode = 'en-us'
title = 'mattmc3.github.io'
theme = ["github.com/tomowang/hugo-theme-tailwind"]
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:slug/'
  [permalinks.section]
    posts = '/articles/'

[menu]
  [[menu.main]]
    identifier = "post"
    name = "Posts"
    pageRef = "/posts"
    weight = 0

[markup]
  [markup.highlight]
    # modus-vivendi, doom-one2, solarized-dark256, dracula, witchhazel, hrdark, github-dark
    style = 'modus-vivendi'
