baseURL = 'https://mattmc3.github.io/'
languageCode = 'en-us'
title = 'mattmc3.github.io'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:slug/'
  [permalinks.section]
    posts = '/articles/'
