baseURL = 'https://mattmc3.github.io/'
languageCode = 'en-us'
title = 'mattmc3.github.io'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:slug/'
  [permalinks.section]
    posts = '/articles/'

[markup]
  [markup.highlight]
    # modus-vivendi, doom-one2, solarized-dark256, dracula, witchhazel, hrdark, github-dark
    style = 'github-dark'
